### ISSUE TITLE
Replace attribute/varying access with accessor functions

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-sandbox#10]
For platform compatibility (and resiliency to implementation changes), we need to replace accesses of attributes and varyings with new accessor functions.
- `a_position` replaced by `modelPosition()`
- `v_world_position` replaced by `worldPosition()`
- `a_normal`/`v_normal` replaced by `worldNormal()` (accounts for view matrix transforms)

https://github.com/tangrams/tangram-sandbox/search?utf8=%E2%9C%93&q=a_position
https://github.com/tangrams/tangram-sandbox/search?utf8=%E2%9C%93&q=v_world_position
https://github.com/tangrams/tangram-sandbox/search?utf8=%E2%9C%93&q=v_normal&type=Code

**Comment by bcamper** [comment]
Just realized, before getting ahead of myself -- `worldNormal()` PR is merged in JS, but awaiting 0.4.1 release! The other two are already in 0.4.0.

https://github.com/tangrams/tangram/pull/209

**Comment by patriciogonzalezvivo** [comment]
:+1: 
https://github.com/tangrams/tangram-sandbox/commit/0d3107620c5b85d2c7fc970a6c1ad08e34e512b5
