### ISSUE TITLE
Demos broken, reference defunct tile.mapzen.com

### ISSUE THREAD

**Issue by mootari** [tangrams/tangram-sandbox#19]
Many (all?) demos reference the domain tile.mapzen.com which no longer exists.

**Comment by nvkelso** [comment]
@meetar can you update the URLs in this repo to Nextzen, please? Looks like most the other repos were already updated :)

**Comment by meetar** [comment]
@nvkelso Do you know whether this demo is being hosted publicly anywhere? If so do you know whether it's pulling straight from this repo, or possibly referencing an explicit commit, as with the carousel?

**Comment by nvkelso** [comment]
I assume from Github pages:

![image](https://user-images.githubusercontent.com/853051/59223536-04dac900-8b81-11e9-9eb3-d85032967402.png)

But @mootari to confirm where it was observed.

**Comment by mootari** [comment]
> I assume from Github pages

Yup, here are a few broken examples:
- https://tangrams.github.io/tangram-sandbox/tangram.html?styles/tilt-gotham#16/40.7083/-73.9968
- https://tangrams.github.io/tangram-sandbox/tangram.html?styles/radar#10/40.7461/-74.0931
- https://tangrams.github.io/tangram-sandbox/tangram.html?styles/press#10/40.7461/-74.0931

**Comment by meetar** [comment]
Urls updated.

**Comment by mootari** [comment]
Thank you! The overview at https://tangrams.github.io/tangram-sandbox/ is still referencing a [missing stylesheet](https://github.com/tangrams/tangram-sandbox/blob/4dd4cc6511d5f422ea4bc701a1208cfc72aee333/index.html#L8) from the defunct mapzen styleguide. However the compiled CSS file can be obtained through the wayback machine: https://web.archive.org/web/20180102172122cs_/https://mapzen.com/common/styleguide/styles/styleguide.css

**Comment by meetar** [comment]
True enough! I'm fine to let that one be.

**Comment by mootari** [comment]
May I suggest simply replacing the current stylesheet URL with the archive.org one? archive.org explicitely allows hotlinking, and the other script URL is already pointing to rawgit.com.

**Comment by s-light** [comment]
#21 fixes this by removing all the *custom* rendering / styling of the index.html. just leaving this to the default jekelly theme. at least this way it works again.
